// <auto-generated />
using System;
using Duett_Server_Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuettServerDomain.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20221220025900_sqlite.local_migration_659")]
    partial class sqlitelocalmigration659
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Duett_Server_Domain.Models.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b18357f1-567c-4743-b8b3-cf24ac4fdac4"),
                            AValue = 15,
                            BValue = 25,
                            Description = "Banana"
                        },
                        new
                        {
                            Id = new Guid("c83c79b8-ab04-4c0c-9987-b15c15471b66"),
                            AValue = 8,
                            BValue = 12,
                            Description = "Pêra"
                        },
                        new
                        {
                            Id = new Guid("c45d13ee-cf51-4da4-a5d9-4df25f99e7ec"),
                            AValue = 35,
                            BValue = 10,
                            Description = "Abacaxi"
                        },
                        new
                        {
                            Id = new Guid("0e6e811e-c466-4eaf-a259-c1b6ecb2ae51"),
                            AValue = 30,
                            BValue = 14,
                            Description = "Maçã"
                        },
                        new
                        {
                            Id = new Guid("7ab83819-a14b-452e-a4eb-7bde89bd0f5a"),
                            AValue = 17,
                            BValue = 73,
                            Description = "Uva"
                        },
                        new
                        {
                            Id = new Guid("bfa1d80d-5c24-42b1-b747-02d713479487"),
                            AValue = 8,
                            BValue = 1,
                            Description = "Melancia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
