// <auto-generated />
using System;
using Duett_Server_Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuettServerDomain.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20221220001944_add-seed")]
    partial class addseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Duett_Server_Domain.Models.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc78a37d-838a-47b9-8f6c-8f824c97aebf"),
                            AValue = 15,
                            BValue = 25,
                            Description = "Banana"
                        },
                        new
                        {
                            Id = new Guid("cbb379f6-dad9-4730-b526-092028bf6c29"),
                            AValue = 8,
                            BValue = 12,
                            Description = "Pera"
                        },
                        new
                        {
                            Id = new Guid("2956395b-8f6a-4e06-8472-d70ad184e815"),
                            AValue = 35,
                            BValue = 10,
                            Description = "Abacaxi"
                        },
                        new
                        {
                            Id = new Guid("ce97032e-e752-4924-9bae-3e07cd833115"),
                            AValue = 30,
                            BValue = 14,
                            Description = "Maça"
                        },
                        new
                        {
                            Id = new Guid("0837b971-8874-41da-a3e0-29d4ab98f34a"),
                            AValue = 17,
                            BValue = 73,
                            Description = "Uva"
                        },
                        new
                        {
                            Id = new Guid("ca62e688-cf16-4f32-ac3c-0a5d652d5e5f"),
                            AValue = 8,
                            BValue = 1,
                            Description = "Melancia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
