// <auto-generated />
using System;
using Duett_Server_Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuettServerDomain.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20221220002101_updated-seed")]
    partial class updatedseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Duett_Server_Domain.Models.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49fe3d00-d7b8-401e-9b9a-f2a31bb1d1cb"),
                            AValue = 15,
                            BValue = 25,
                            Description = "Banana"
                        },
                        new
                        {
                            Id = new Guid("bd7308c5-f486-4d62-b291-24bb27892331"),
                            AValue = 8,
                            BValue = 12,
                            Description = "Pêra"
                        },
                        new
                        {
                            Id = new Guid("7a697737-afb8-45c8-81ed-7f761ca6e270"),
                            AValue = 35,
                            BValue = 10,
                            Description = "Abacaxi"
                        },
                        new
                        {
                            Id = new Guid("36923066-5050-4a24-ba89-bc663fe9a722"),
                            AValue = 30,
                            BValue = 14,
                            Description = "Maçã"
                        },
                        new
                        {
                            Id = new Guid("c22e1cf5-8dc3-42b4-bdef-2aff5b8e59b1"),
                            AValue = 17,
                            BValue = 73,
                            Description = "Uva"
                        },
                        new
                        {
                            Id = new Guid("386396c0-1f10-46c7-88a7-c6eb771078d4"),
                            AValue = 8,
                            BValue = 1,
                            Description = "Melancia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
